# ******************************************************************************
#  Unlicensed. Free for usage without warranty, expressed or implied
#
#  Implementation of Conway's Game of Life
#
#  Filename   : cgol_context_menu.py
#  Description:
#    This Python program implements a simple zero-player game known as
#    Conway's Game of Life (CGoL). CGoL was devised by John Horton Conway in
#    1970.  https://en.wikipedia.org/wiki/Conway's_Game_of_Life
#
#    This file implements a context menu that is initiated by the grid panel
#    upon a right-click in the grid
#
#  Change log:
#    2026-09-17  KSM  Created
#
#  Copyright © 2026 Kerry S Martin, wssm243@gmail.com
# ******************************************************************************

import wx
from static_init import static_init

type ContextItemEntry = tuple[str, str, tuple[int,int]]
type ContextResult = ContextItemEntry | int | None


@static_init
class GridContextMenu:

    @classmethod
    def static_init(cls):
        cls.__MENU_ENTRIES : list[ContextItemEntry] = [

            # Non-pattern entries: ("label", "", (-1,val))   val is return value
            ( "Clear grid", "", (-1,0) ),

            # Separator entry: ("", "", (-1,-1))
            ( "", "", (-1,-1) ),

            # Pattern entries: ("label", "pattern", (row,col))  row,col designates head of structure
            ( "Glider", "x.x\n.xx\n.x.", (2,2) ),
            ( "Beacon", "xx..\nxx..\n..xx\n..xx", (1,1) ),
            ( "Blinker", "xxx", (0,1) ),
            ( "Block", "xx\nxx", (0,0) ),
            ( "Beehive", ".xx.\nx..x\n.xx.", (1,1)),
            ( "Tub", ".x.\nx.x\n.x.", (1,1)),
            ( "Toad", ".xxx\nxxx.", (0,1)),
            ( "Bowtie", ".xx\nx.x\nxx.", (1,1))
        ]


    def __init__(self, parent:wx.Panel):
        """Constructor for class to generate grid context menu

        Args:
            parent: [wx.Panel]  panel context menu is assigned to
        """
        menu = wx.Menu()
        self.__menu_table : dict[int, ContextItemEntry] = dict()
        for entry in GridContextMenu.__MENU_ENTRIES:
            label = entry[0]
            if label:
                item = menu.Append(wx.ID_ANY, label)
                id = item.GetId()
                self.__menu_table[id] = entry
            else:
                menu.AppendSeparator()
        menu.Bind(wx.EVT_MENU, self.__on_menu_click)
        self.__menu : wx.Menu = menu
        self.__parent : wx.Panel = parent
        self.__result : ContextResult = None


    def __del__(self):
        """Destructor
        """
        self.__menu.Destroy()


    def show_context_menu(self, pos:wx.Point) -> ContextResult:
        """Show the context menu at the given location and get its resulting click

        Args:
            pos: _description_

        Returns:
            [None]   if nothing useful was clicked
            [int]    if a non-pattern item was clicked, value=from entry
            [tuple]  (label, pattern, head)
                     head = (row, col) of the pattern cell designated as the head
        """
        self.__result = None
        self.__parent.PopupMenu(self.__menu, pos)
        return self.__result


    def __on_menu_click(self, event:wx.CommandEvent):
        """Handler for a click on a menu item

        Args:
            event: [wx.CommandEvent]  event generated by the item click
        """
        item_id = event.GetId()
        if item_id in self.__menu_table:
            entry = self.__menu_table[item_id]
            label, pattern, pos = entry
            if not pattern:
                # non-pattern item, return int or None
                self.__result = pos[1] if label else None
            else:
                # pattern item, return the entry
                self.__result = entry


# ******************************************************************************
#  Copyright © 2026 Kerry S Martin, wssm243@gmail.com
#  Unlicensed. Free for usage without warranty, expressed or implied
# ******************************************************************************